export default {
  //   login: "vasil-yordanov14",
  //   id: 96545262,
  //   node_id: "U_kgDOBcEp7g",
  //   avatar_url: "https://avatars.githubusercontent.com/u/96545262?v=4",
  //   gravatar_id: "",
  //   url: "https://api.github.com/users/vasil-yordanov14",
  //   html_url: "https://github.com/vasil-yordanov14",
  //   followers_url: "https://api.github.com/users/vasil-yordanov14/followers",
  //   following_url:
  //     "https://api.github.com/users/vasil-yordanov14/following{/other_user}",
  //   gists_url: "https://api.github.com/users/vasil-yordanov14/gists{/gist_id}",
  //   starred_url:
  //     "https://api.github.com/users/vasil-yordanov14/starred{/owner}{/repo}",
  //   subscriptions_url:
  //     "https://api.github.com/users/vasil-yordanov14/subscriptions",
  //   organizations_url: "https://api.github.com/users/vasil-yordanov14/orgs",
  //   repos_url: "https://api.github.com/users/vasil-yordanov14/repos",
  //   events_url: "https://api.github.com/users/vasil-yordanov14/events{/privacy}",
  //   received_events_url:
  //     "https://api.github.com/users/vasil-yordanov14/received_events",
  //   type: "User",
  //   site_admin: false,
  //   name: "Vasil Vasilev",
  //   company: null,
  //   blog: "linkedin.com/in/vasil-vasilev-284aa820b",
  //   location: "Sofia, Bulgaria",
  //   email: null,
  //   hireable: null,
  //   bio: null,
  //   twitter_username: null,
  //   public_repos: 26,
  //   public_gists: 0,
  //   followers: 0,
  //   following: 0,
  //   created_at: "2021-12-22T18:27:59Z",
  //   updated_at: "2022-07-31T19:41:15Z",
  // };

  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
